### ISSUE TITLE
Display amount of zoom

### ISSUE THREAD

**Issue by acomrie** [magland/sortingview#101]
Hello, would it be possible to display the zoom level a user is currently using for any of the sortingview views? A zoom reset button could also work for this. I'd like to be able to use consistent zoom level throughout curation of a given dataset so that I don't bias my curation depending on the zoom level. However, occasionally, I may wish to zoom in or out to highlight some feature, and then I may lose track of how zoomed in or not I am. This feature would simply increase user friendliness. Thank you for considering!

**Comment by magland** [comment]
I think we should implement a zoom reset button. @jsoules I'll assign this to you, but I'm guessing there will be some discussion about exactly what the behavior should be and where the button should reside.
