### ISSUE TITLE
Show waveform on chans above and below peak chan in no-geom view

### ISSUE THREAD

**Issue by acomrie** [magland/sortingview#103]
I think the current behavior of average waveform view is that channels both above and below the peak amplitude channel are displayed when possible. However, for long skinny electrode geometries with many channels, I find it much easier to visualize the average waveforms by unchecking the "use electrode geom" waveform option. In this view, the peak channel is always displayed at the top, and I can see the average waveform on any channels below the peak amplitude channel (but not above). It would be helpful to see the average waveform on channels both above and below the peak amplitude channel in this no-geom view, too. That said, it is handy to know which channel has the peak amplitude without having to reference the units table, so perhaps that info could be retained in the average waveform view by bolding the channel ID number displayed next to each channel's average waveform. Thoughts?  Thanks! (see for ex: https://sortingview.vercel.app/workspace/sorting/R-c5089c48b72f/S-816a8e175985?workspace=e5c306c436a9f75fd97a20d832cd54d8243d516da53cbfe86270f11e98ee8b26&channel=franklab)

**Comment by magland** [comment]
I may not be quite understanding but.... would it be sufficient to order the "no-use-geom" view in ascending order by channel ID?

**Comment by acomrie** [comment]
Thanks. After seeing your comment I looked back and realized that I had been falsely assuming that the channel ID ordering was always ascending, which is clearly not the case now that I am looking back at it! I'm sorry for not paying more attention beforehand. I suppose I do think ordering by channel ID in the no-use-geom view would be intuitive (but potentially only because in my use case with a linear probe channel arrangement, this basically makes the no-use-geom display correspond to the probe's geom...). Thoughts on that? Not sure of the history of the use vs no-use geom options, and perhaps I'm interacting with them incorrectly.

I really liked being able to view the waveform across the neighboring channels in qt-mountainview with that vertical panel arrangement of the average waveforms. In sortingview, with 32 channels in a linear arrangement per probe shank, the default geom waveform view just makes the waveforms too tiny to actually see and evaluate them in the little circles. That is why I have been using the no-use-geom view instead. Thanks in advance for your thoughts, @magland

**Comment by magland** [comment]
I think it makes sense to sort by channel ID, and that's pretty easy to do. We'll make the change and then we'll see how well that works.

**Comment by magland** [comment]
Opening a new issue to put the geom-layout option button on the toolbar of the avg waveforms widget (for convenience).

**Comment by acomrie** [comment]
Hi @magland, I am wondering when this ordering of the no-use-geom view might be implemented? Thank you for any estimates or updates!
