### ISSUE TITLE
put the geom-layout option button on the toolbar of the avg waveforms widget

### ISSUE THREAD

**Issue by magland** [magland/sortingview#106]
Opening a new issue to put the geom-layout option button on the toolbar of the avg waveforms widget (for convenience).

_Originally posted by @magland in https://github.com/magland/sortingview/issues/103#issuecomment-895520112_

**Comment by jsoules** [comment]
I'm not sure what this is referring to--is this the checkbox under the 'Options' sidebar that says "Waveforms: Use electrode geom"?

**Comment by jsoules** [comment]
See [figurl issue #7](https://github.com/magland/figurl/issues/7) and [PR #9](https://github.com/magland/figurl/pull/9).
