### ISSUE TITLE
Errors in autocorrelation calculation  /display

### ISSUE THREAD

**Issue by lfrank** [magland/sortingview#11]
In some cases a unit's autocorrelation can be very strange: 
<img width="376" alt="Screen Shot 2021-07-05 at 6 21 54 PM" src="https://user-images.githubusercontent.com/7063497/124528881-263d2c00-ddbe-11eb-8af7-e766d92f8ebc.png">

Here's the link to the workspace:
https://sortingview.vercel.app/workspace/sorting/R-1ac0e7153ac0/S-b5b3168133d0?workspace=1a89e449d88d217fb77be62fac75bbde66adec69f83969c3019f33e03c436c6c&channel=franklab

**Comment by magland** [comment]
This was an integer overflow error. I fixed it, but you need to upgrade sortingview to 0.2.13.

(There's a bit of a difficulty with this flow, where the front-end version needs to match with the back-end version. We'll need to work out how best to manage this. Right now, both should be at 0.2.13)

**Comment by magland** [comment]
This appears to still be a problem -- i will continue to investigate.

**Comment by magland** [comment]
I believe this should be fixed once you've upgraded to >= 0.2.17 on the backend

@lfrank @khl02007

**Comment by magland** [comment]
I can confirm this has been fixed (same link as above):

![image](https://user-images.githubusercontent.com/3679296/124630919-deb3b000-de50-11eb-9428-9a3672b62ac2.png)
