### ISSUE TITLE
Error opening a workspace

### ISSUE THREAD

**Issue by khl02007** [magland/sortingview#118]
I get the following error when trying to open this workspace

Error:
```
Error in task fetch_spike_amplitudes.1: Error running job (pjh): index 54154 is out of bounds for axis 0 with size 54154
```

workspace:
https://sortingview.vercel.app/workspace/sorting/R-c8582d7c7cfe/S-85e9bced8e92?workspace=454d5615cb5d485dcfecfbc0ff98ef597d5cf841fc1f5ee86259ebf361a41564&channel=franklab

**Comment by magland** [comment]
What do you mean by "opening workspace". Are you talking about opening it in python? If so, could you provide the script?

**Comment by khl02007** [comment]
By opening I mean opening the workspace on the browser. It used to stall and give that error message at the top left after computing snippets. It seems to be resolved now so closing.
