### ISSUE TITLE
Kachery processes overloading server

### ISSUE THREAD

**Issue by acomrie** [magland/sortingview#120]
Typhoon, the computer that is running the kachery client and that handles all things sortingview in the lab, has crashed several times in the past week. This seems to arise because many kachery processes are running, consuming too much memory.

Many processes are presumably running because I and others are interacting with sortingview, testing and curating data. In one of the recent crashes, our system administrator said that the out-of-memory killer was invoked, and that he observed >50 processes running, each consuming >40 GB, maxing out the full 2 TB memory available and using all the swap space. These crashes not only disrupt sortingview for us, but also disrupt our access to our mySQL database server and anything else running on that machine, so I think this is relatively high priority.

For the time being, @khl02007 has modified a config file to control the number of such processes that can run on typhoon at a time, which should definitely help avoid crashing. In addition, I and other lab members can do our best to limit the number of sortingview windows we open at any given time.

When brainstorming with @lfrank, we weren't sure if leftover processes can build up over time too (totally guessing, but something like in #116 perhaps,  where incomplete tasks that always stay "waiting" could potentially hang around longer than needed?). 

Any thoughts about what else can be done to be careful about the number of kachery processes running and kachery's overall memory usage? Thanks so much.

**Comment by magland** [comment]
We may have some sort of memory leak, or process accumulation leak as you say. I am marking this as high priority and we'll work out how to best diagnose/fix the issue.

**Comment by magland** [comment]
Not sure if this is still an issue, but the next step will be to use per user backend IDs. Closing.
