### ISSUE TITLE
Show all units for waveform and autocor views

### ISSUE THREAD

**Issue by acomrie** [magland/sortingview#121]
Would be a nice feature if possible to have a "show all" option rather than (or in addition to) the "show more" option for displaying units' waveform and autocorrelogram views. It's not clear to me when a user would want to look at just the first 30 units, or the first 30 units plus the next 60 units, etc. - what is the thinking behind this?

Although I have at times wanted to view a subset of the units, that subset is usually by label or metric, not by increasing unitID. Perhaps for computational reasons it is better to load smaller chunks up at a time rather than all at once. That said, for now, I have just been selecting show more, scrolling down, selecting show more again, scrolling down, and repeating until all units' plots are displayed. Pressing "show all" once (like in the units table) and then simply waiting longer for them all to load up in chunks would be a bit easier/faster.

**Comment by magland** [comment]
Okay, will switch "show more" to "show all".

**Comment by jsoules** [comment]
See [figurl PR #6](https://github.com/magland/figurl/pull/6).
