### ISSUE TITLE
Open a few different xcorr simultaneously

### ISSUE THREAD

**Issue by acomrie** [magland/sortingview#123]
Is it possible to open two xcorr views, each showing plots for different subsets of units? Selection of units across two xcorr views currently appears to be locked together, so that if the units selected in one view change, the selected units also change in the other xcorr view, too. I understand how this locking is useful across different types of views; however, I might be misunderstanding why it is useful / why it must be this way when two of the same view are open. Thanks for any thoughts on this!

**Comment by jsoules** [comment]
Thanks for raising this (as well as the number of other great issues you've been bringing up over the last couple days).

Fortunately, this one is already supported--if you pull up the cross-correlogram view, above the unit selection list on the left you'll see a little slider labeled 'lock selection.' When it's deactived (the default), the selection state will be synced with the global selection state (used on the units table, autocorrelograms, etc. etc.)

However, once you have a selection for your xcorr, activating 'lock selection' will keep that selection constant. It will no longer sync to the global state, and you won't be able to alter it in the widget either (so stray clicks won't change your locked view).

![image](https://user-images.githubusercontent.com/2347301/130248181-6939392f-f20e-4d39-ab8f-b54853ec76b9.png)

If you unlock the selection, it'll then automatically sync back to the global state and resume following changes made in other views.

**Comment by acomrie** [comment]
Got it - makes sense and seems to work smoothly! Thanks.
