### ISSUE TITLE
Full zoom out on spike amplitude view

### ISSUE THREAD

**Issue by acomrie** [magland/sortingview#126]
A request on behalf of @rsnevers and I -- it would be nice to be able to fully zoom out of the spike amplitude view to see spikes from the full length of the recording. The zoom out button seems to max out at a point where a user can still scroll left to right through time, like so -
<img width="1252" alt="Screen Shot 2021-08-20 at 4 18 22 PM" src="https://user-images.githubusercontent.com/46034181/130302002-93384333-7624-4dcc-b36f-ddd1b6224a9d.png">

Yet it also seems like a user can edit the time range at the bottom to a falsely large upper limit, and force this fully zoomed out display -
<img width="1252" alt="Screen Shot 2021-08-20 at 4 17 33 PM" src="https://user-images.githubusercontent.com/46034181/130302053-eb4cca46-4183-44e6-ba06-f0f748db2a5f.png">

@rsnevers does that align with your experience?

Wondering if there is any reason not to enable fully zooming out with the zoom-out button? If not, would be great to enable that. It can be helpful to see super slow timescale changes in spike amplitude that occur over the course of a few hours of a recording in this zoomed out view. Thanks in advance for your thoughts.

**Comment by magland** [comment]
@acomrie. I think we can do this. Here are the considerations.

The reason for the limit is to avoid excessive queuing of tasks for computing data (it takes more tasks to retrieve a larger time interval). This is mainly relevant for the timeseries view (raw traces) - much more so than the spike amplitude view.

But the spike amplitude and timeseries views are synchronized. So it's difficult to have a separate limit for the two views. But I wonder if this can be achieved in a nice way. Here's what I propose:

* The limit can be removed from the spike amplitude view, but still retained in the timeseries view.
* If we are zooming in the timeseries view, the zoom-out is blocked beyond a certain point
* If we are zooming in the spike amp view, the zoom-out is not blocked
* If we are zoomed out past the limit of the timeseries view, the timeseries data are not computed, and we get a message to the effect of "cannot display data at this zoom level".

What do you think @acomrie, @rsnevers, @jsoules ?

**Comment by acomrie** [comment]
That makes sense and sounds good. I especially like the idea to add a message to alert the user to the zoom limit.

Another idea would be to control whether the two views are timelocked by a toggle button like the one in the xcorr view that controls unit selection. Sortingview could alert the user that the two views (timeseries and spike amplitude) need to be unlocked to allow further zoom out of the spike amplitude view. That wouldn't have much added benefit over what you already proposed though, other than potentially allowing more views to simultaneously be open and displayed with independent time axes, and seems more difficult to implement. So, probably still makes sense to go with your suggestion!
