### ISSUE TITLE
Snippet width adjustability

### ISSUE THREAD

**Issue by magland** [magland/sortingview#13]
From: https://github.com/flatironinstitute/labbox-ephys/issues/479

Right now it looks like the snippets are ~100 point long, and that's quite a lot longer that we find useful. Would it be possible to pass in / set a parameter for snippet size?

**Comment by magland** [comment]
@lfrank, I'm trying to figure out where is the best place to set this parameter. Many of the visualizations and calculations depend on the same extract-snippets step. Here are the choices to consider:

* Just change the default (easiest but least versatile)
* Option in the sorting view window / sorting-specific - annoying to always manually be setting this
* Attach it as a property of the recording - convenient perhaps, but doesn't belong there
* Attach it as a property of the workspace - could work
* Make it a configurable setting of the kachery channel - bad idea

I think making it an adjustable property of the workspace might be the best approach

**Comment by lfrank** [comment]
I agree that have it as a parameter of the workspace makes sense, but I will note that it is also a parameter of the sorting, albeit one that isn’t currently saved. We of course have it stored as a sorting parameter, so we can add it to the workspace after we create it.

>

**Comment by magland** [comment]
As of sortingview >= 0.2.19, you can set the snippet_len parameter on a workspace. Instructions for doing this are on the web app on the workspace page.

See: https://sortingview.vercel.app/workspace?workspace=1a89e449d88d217fb77be62fac75bbde66adec69f83969c3019f33e03c436c6c&channel=franklab

Will close after get confirmation from Frank lab that it works

**Comment by khl02007** [comment]
I just tried this and can confirm that this works. But it would be more convenient if the snippet size could be set on the web app rather than via python.

**Comment by magland** [comment]
> I just tried this and can confirm that this works. But it would be more convenient if the snippet size could be set on the web app rather than via python.

That is difficult because the snippets is a big pre-calculation. I am going to close this issue for now, but you can open another issue if you have an idea for how to make the snippet size easier to use.

**Comment by khl02007** [comment]
Is it slower to take longer snippets vs. shorter snippet? I wonder if we can just take relatively long snippets for the pre-calculation (e.g. +/-  5 ms of the spike time) and then allow the user on the web app to zoom in (i.e. use shorter snippet) if necessary. This may increase the size of cached file but hopefully it's not too large.
