### ISSUE TITLE
Sortingview not working

### ISSUE THREAD

**Issue by khl02007** [magland/sortingview#131]
using sortingview 0.3.1, kachery daemon 1.0.24

getting this error from sortingview backend:
```
{'success': False, 'error': 'Error posting json: 500 Invalid request in _handle>
Unexpected error registering tasks with kachery daemon.
Will retry in 10 seconds
```

getting this error on the kachery daemon side:
```
Daemon responding with error: 500 Invalid request in _handleTaskRegisterTaskFun>
```

**Comment by lfrank** [comment]
As a follow up, we also get the following when we start the current version of kachery daemon, and I'm not sure whether any of this is relevant, although it seems unlikely to be related to this issue:
+ npm install -g -y /home/kacheryuser/miniconda3/envs/kachery-env/lib/python3.8/site-packages/kachery_daemon/kachery-daemon-node-1.0.24.tgz
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated node-pre-gyp@0.11.0: Please upgrade to @mapbox/node-pre-gyp: the non-scoped node-pre-gyp package is deprecated and only the @mapbox scoped package will recieve updates in the future
npm WARN deprecated tar@2.2.2: This version of tar is no longer supported, and will not receive security updates. Please upgrade asap.
+ exec kachery-daemon-node start --verbose 0 --auth-group kachery-users --kachery-hub-url https://kacheryhub.org --label franklab --owner kyuhyun9056@gmail.com

**Comment by magland** [comment]
Please upgrade to kachery-daemon >= 1.0.25 and restart the daemon.

**Comment by lfrank** [comment]
It seems to be running now, so thank you, although I'm getting the following odd error for a couple of units when I tried to look at the average waveforms

Error running fetch avg waveform: Error running job (pjh): 'NoneType' object is not subscriptable.

**Comment by magland** [comment]
Glad that's working. When I click on the link I am able to see all the avg waveforms (not able to reproduce that error)

**Comment by lfrank** [comment]
As am I now. I don’t understand what changed, and I’ll let you know if it happens again...
