### ISSUE TITLE
Error in sortingview when trying to get recording info

### ISSUE THREAD

**Issue by lfrank** [magland/sortingview#135]
After adding a  LabBoxEphysRecordingExtractor to a workspace, I get an error in sortingview:

	8db5eba88b70d797f1706d958af58c4b81b61184	recording_info.3	error	no	3:31:55 PM		Problem updating task status to finished: Out of range float values are not JSON compliant

I can, however, get the recording extractor in python and, for example, get_channel_ids() successfully

Here is the workspace:
https://sortingview.vercel.app/workspace?workspace=workspace://ba025eef3276d556a07615356a471ae3a57ac5fec45dfe3d14c72ba4d31c8a1b?label=despereaux20191125_9OON0CASZ8.nwb&channel=franklab

**Comment by magland** [comment]
One of the following quantities in the below dict must be `NaN`. Could you please figure out which one it is?

```python
from typing import List, cast
import numpy as np
import spikeextractors as se

def estimate_noise_level(recording: se.RecordingExtractor):
    N = cast(int, recording.get_num_frames())
    samplerate = cast(float, recording.get_sampling_frequency())
    start_frame = 0
    end_frame = np.minimum(int(samplerate), N)
    X = cast(np.ndarray, recording.get_traces(channel_ids=[int(id) for id in cast(List[int], recording.get_channel_ids())], start_frame=start_frame, end_frame=end_frame))
    X_mean_subtracted = _mean_subtract_on_channels(X)
    est_noise_level = np.median(np.abs(X_mean_subtracted.squeeze())) / 0.6745  # median absolute deviation (MAD) estimate of stdev
    if (est_noise_level == 0): est_noise_level = 1
    return est_noise_level

dict(
        sampling_frequency=recording.get_sampling_frequency(),
        channel_ids=recording.get_channel_ids(),
        channel_groups=recording.get_channel_groups().tolist(),
        geom=geom_from_recording(recording).tolist(),
        num_frames=recording.get_num_frames(),
        noise_level=estimate_noise_level(recording),
        recording_object=recording.object()
)
```

**Comment by magland** [comment]
The problem was that the elec geom was not being included in the h5_v1 format.

Please upgrade to sortingview >= 0.6.4 and then regenerate the .h5 file. Also restart the backend after upgrading.

(There may be an issue with the old backend still running, because that won't have the patch. It's tricky, let's discuss on slack.)
