### ISSUE TITLE
backend task not registering

### ISSUE THREAD

**Issue by khl02007** [magland/sortingview#143]
@magland I restarted kachery daemon and sortingview backend but the tasks are not registered
<img width="598" alt="image" src="https://user-images.githubusercontent.com/9277197/133480485-b7314ab4-c373-4a16-a924-a9df9409a896.png">
output from sortingview backend
<img width="1218" alt="image" src="https://user-images.githubusercontent.com/9277197/133480523-7064f8bc-b199-4522-91a4-e397654218bc.png">

**Comment by magland** [comment]
This has been resolved. Closing.
