### ISSUE TITLE
trigger precomputation of key views

### ISSUE THREAD

**Issue by lfrank** [magland/sortingview#144]
Given that precomputing snippets, unit waveforms and autocorrelations can take some time, it would be helpful to be able to request that those computations be done and cached before opening up the figurl window.

**Comment by magland** [comment]
@lfrank I think this should do the trick: https://github.com/magland/sortingview/wiki/workspace-precalculation

**Comment by lfrank** [comment]
@magland Thanks; that works nicely, and indeed if we could pass in some arguments to indicate which things we’d like to precompute (snippets, waveforms, autocorrelations, others) that would be ideal. I’ll add an issue.
