### ISSUE TITLE
set_snippet_length should apply when use electrode geometry is not checked

### ISSUE THREAD

**Issue by lfrank** [magland/sortingview#148]
see https://www.figurl.org/fig?channel=franklab2&figureObject=b8272e7f30c2cf325ed9d3257cea10fac1e0998d&label=despereaux20191125_.nwb_02_r1_13 for an example where snippet length has been set to (20,20)

**Comment by magland** [comment]
@lfrank I believe that the correct snippet len is actually being applied in both situations. Could it be an illusion of the display?

**Comment by lfrank** [comment]
Ah, you’re right. Sorry for my error. Would it be possible to add a horizontal scale so that the waveforms could be compressed on the x-axis?

**Comment by magland** [comment]
I'll open an issue for that request.
