### ISSUE TITLE
Window height adjustment doesn't work

### ISSUE THREAD

**Issue by lfrank** [magland/sortingview#15]
The center bar is currently not movable, so the relative heights of the two visualization windows cannot be changed.

**Comment by magland** [comment]
Deployed a quick fix, no need to update backend. For example: https://sortingview.vercel.app/workspace/sorting/R-2562bd03a29f/S-8906190e4b1b?workspace=af3bee331a971f57877f857a6da7c268bcef70dda0af70a8367cbae8675cb5de&channel=ccm
