### ISSUE TITLE
int16 extractor issues

### ISSUE THREAD

**Issue by lfrank** [magland/sortingview#152]
Using an int16 extractor seems faster (and certainly reduces files sizes, which is very helpful) but also causes various division by zero errors in sorting view: 

https://www.figurl.org/fig?channel=franklab2&figureObject=9c35a6a5ea204bcaf37e7a4695991801b4eb51b3&label=despereaux20191125_.nwb_02_r1_2

**Comment by magland** [comment]
Could you please specify which views exactly are giving the divide-by-zero errors?

**Comment by lfrank** [comment]
Sorry for not specifying.

And now everything calculates correctly, which makes me wonder if it might be due to different versions of the sortingview backend on our side. I’ll investigate when I can.

**Comment by magland** [comment]
Closing. Feel free to reopen if needed.
