### ISSUE TITLE
Setting for neighborhood size

### ISSUE THREAD

**Issue by lfrank** [magland/sortingview#155]
For our larger recordings we need the ability to set a smaller neighborhood size for snippet extraction, as otherwise we are running out of RAM.

**Comment by lfrank** [comment]
That makes sense, but I worry about the impact on manual curation time. I can imagine ways that we could propagate labels from one chunk to the next (assuming the sort was done on a longer chunk) but it certainly would be nice to have a single solution that could make it easy to track units through.

**Comment by magland** [comment]
I believe this is resolved. Closing for now.
