### ISSUE TITLE
Can't curate on figurl

### ISSUE THREAD

**Issue by xlsun79** [magland/sortingview#157]
When trying to curate a new sort in figurl today, I found that there was no curation button. I set the permission to true when running SpikeSortingWorkspace, and I also followed the instructions on figurl to make sure that my email address has the permission. But I still don't see the curation button. What could be the issue? Thank you!

**Comment by magland** [comment]
@xlsun79 @khl02007 please try now. I'm pretty sure I fixed it. (No need to update the backend, this was an issue with the GUI)
