### ISSUE TITLE
Add sorting_id argument to precalculate function

### ISSUE THREAD

**Issue by dpeg22** [magland/sortingview#160]
When two different sortings exist (with different sort parameter sets) in the same workspace, precalculate will run on the first sort, but not the second. When running precalculate on the workspace after the second sort is added, it prints that it is running on the first sort and the hither print out is this:
![hither job print out](https://user-images.githubusercontent.com/57648931/141178051-b4ec8529-9b18-443e-ad6e-284ff609436b.png)
A sorting_id argument will hopefully be able to get around this.

**Comment by magland** [comment]
The intended functionality is that it will run precalculate on all of the sortings in the workspace. When I look at the source code I'm pretty sure that's what it's doing. Should print out for each one:
`Precalculating: {recording_label}/{sorting_label}`

Could you post the entire console output?

**Comment by dpeg22** [comment]
Here is the output using the nwb_datajoint table SpikeSortingWorkspace to call the precompute function:
![precalculate_error](https://user-images.githubusercontent.com/57648931/141194183-ffa83e96-cad3-4c6b-b33f-bb5f5185c770.png)
'mountainsort4_JG_DG_probe_cortex_30KHz_115' is the name of the first spikesorter parameter set. The errored number increases each time I run the command.
