### ISSUE TITLE
average waveform not displaying properly

### ISSUE THREAD

**Issue by khl02007** [magland/sortingview#161]
@magland 

figurl: https://www.figurl.org/f?v=gs://figurl/sortingview-gui-1&d=39e15b5fca0bc8215dba367a6cab0ef6ce645cbc&channel=franklab2&label=3rd

What is shown in sortingview:
<img width="177" alt="image" src="https://user-images.githubusercontent.com/9277197/141182316-589979be-4d05-40a3-b7e4-ac492f900d81.png">

What should be shown:

<img width="958" alt="image" src="https://user-images.githubusercontent.com/9277197/141182583-e0991911-dc9d-4bc3-a1b5-e5fc1cb1a1c9.png">

**Comment by magland** [comment]
Resolved
