### ISSUE TITLE
Preload_extract_snippets.2 fails with small cluster

### ISSUE THREAD

**Issue by dpeg22** [magland/sortingview#162]
When opening sorting (mountainsort4_JG_DG_probe_cortex_30KHz) in [figurl](https://www.figurl.org/f?v=gs://figurl/sortingview-gui-1&d=a59ea47b8e805d70f599adeb1cdfa9c03f68dd47&channel=franklab2&label=J1620210606_.nwb_raw%20data%20valid%20times%20no%20pre%20maze%20no%20home_24#), preload_extract_snippets.2 fails with message "Error running job (pjh): Peak channel not found for unit 43. This is probably because not enough spikes were found in any segment." Unit 43 has 46 spikes across 12 hours. Most likely the cause of #160

**Comment by magland** [comment]
@dpeg22 
I think you must not be using the latest version of sortingview. Please upgrade to >= 0.6.29, and restart the backend.
