### ISSUE TITLE
Linearized position plot: just use markers - don't connect points

### ISSUE THREAD

**Issue by magland** [magland/sortingview#168]
This is because there are discontinuities in the plot.

![image](https://user-images.githubusercontent.com/3679296/149182122-c61a601b-0480-4d16-b4e4-f3ead9cc53f2.png)

**Comment by jsoules** [comment]
Needs to be an option in the `PositionPlotView` drawing function--flag to connect dots vs. use scatterplot markers.

**Comment by jsoules** [comment]
See SpikeSortingView PR #20.
