### ISSUE TITLE
Linear position plots: top should not be cut off when zoomed out

### ISSUE THREAD

**Issue by magland** [magland/sortingview#169]
![image](https://user-images.githubusercontent.com/3679296/149182432-cad5c7e4-14de-4632-b8f1-1d9750c6a801.png)

**Comment by magland** [comment]
Rather than giving a buffer in the data value range, I think it's better to try to add a bit of margin to the plot widget. Maybe that will fix it.

**Comment by jsoules** [comment]
https://www.figurl.org/f?v=gs://figurl/spikesortingview-1&d=0a3dc827ee0a220362c6474418056aa7102d3433&channel=flatiron1&label=Jaq_03_12_visualization_data as an example FigURL.

**Comment by jsoules** [comment]
Working hypothesis: maybe something to do with the unfortunate interaction of sub-pixel resolution & several sequential observations at the same point?

Consider increasing the thickness of the line by a pixel and see if it goes away?

**Comment by jsoules** [comment]
See SpikeSortingView PR #20.
