### ISSUE TITLE
multi-timeseries view: put zoom/pan toolbar at top

### ISSUE THREAD

**Issue by magland** [magland/sortingview#180]
now that the left toolbars are not shown for the individual panels, a zoom/pan toolbar should be placed at the top... and the buttons should be laid out horizontally rather than vertically.

**Comment by jsoules** [comment]
Example composite view: https://www.figurl.org/f?v=gs://figurl/spikesortingview-1&d=7086880aeb347d2b2a1f71e2638f7560b67e678e&channel=flatiron1&label=Jaq_03_12_visualization_data2

**Comment by jsoules** [comment]
Resolved by SpikeSortingView PR #36.
