### ISSUE TITLE
Label min/max in vertical axis of timeseries panels

### ISSUE THREAD

**Issue by magland** [magland/sortingview#184]
From Loren: For plots where you allow vertical rescaling, could you add ymin and ymax values?

**Comment by jsoules** [comment]
It's not clear to me how this interacts with issue #181.

The only plot where we currently allow manual vertical rescaling is the average waveform plot, but this request doesn't seem germane there.

I think we would be best served by adapting the bottom (time-axis) tick marks to the vertical axis for `TimeseriesView`-derived plots.

**Comment by jsoules** [comment]
Resolved by SpikeSortingView PR #39.
