### ISSUE TITLE
implement position probability / position combo plot

### ISSUE THREAD

**Issue by magland** [magland/sortingview#189]
From slack:

Eric: Would it be possible to plot the linear position on top of the position probability? That would save some room in the view and allow that plot to be much larger.

Jeremy: That sounds like a good idea. But wouldn't it obscure the probability data to some extent? Would you want an on/off toggle for the position overlay?

Eric: It will obscure the probability data but some of the features we care the most about are actually when the decoded position deviates from the actual position, so the comparison is useful. A toggle for on and off would be great though, especially for detecting any multimodal-ness in the distribution.

**Comment by edeno** [comment]
You can just min and max the linear position range and that will give you the range. Normally there is a vector that has all the bin edges for position, but I did not include that in the data I gave you.

**Comment by magland** [comment]
@edeno How does this look (note the toggle checkbox at the bottom)

https://www.figurl.org/f?v=gs://figurl/spikesortingview-3&d=ipfs://bafkreibq35irhf5wlviah7wcnwzuif4hrek6llbvabg35dbkszmks76f2m&project=siojtbyvbw&label=Jaq_03_12_visualization_data

**Comment by edeno** [comment]
I think that looks mostly right?

There seems to be a slight offset of the position to the decoded position, which I think results from all the position bins not being the same size. Most bins are ~2.5 cm, but there are two bins that are 15 cm for computational reasons to prevent smoothing into bins that are not adjacent in 2D space. Here are the position bin edges for the decoded position if that helps:

```
[0.0,
 2.4983037885938533,
 4.9966075771877065,
 7.494911365781574,
 9.993215154375427,
 12.49151894296928,
 14.989822731563134,
 17.488126520156985,
 19.98643030875084,
 22.48473409734471,
 24.98303788593856,
 27.481341674532416,
 29.979645463126268,
 32.47794925172012,
 34.97625304031399,
 37.47455682890783,
 39.972860617501695,
 42.471164406095546,
 44.96946819468941,
 47.467771983283264,
 49.96607577187712,
 52.46437956047099,
 54.96268334906483,
 57.46098713765867,
 59.95929092625254,
 62.45759471484639,
 64.95589850344025,
 67.45420229203411,
 69.95250608062797,
 72.4508098692218,
 74.94911365781567,
 77.44741744640953,
 79.94572123500339,
 82.44402502359725,
 84.94232881219109,
 87.44063260078494,
 89.93893638937882,
 92.43724017797267,
 94.93554396656653,
 97.43384775516036,
 99.93215154375424,
 114.93215154375424,
 117.3803150266334,
 119.82847850951248,
 122.27664199239165,
 124.7248054752708,
 127.17296895814995,
 129.62113244102903,
 132.0692959239082,
 134.51745940678734,
 136.9656228896665,
 139.4137863725456,
 141.86194985542474,
 144.3101133383039,
 146.75827682118305,
 149.20644030406214,
 151.6546037869413,
 154.10276726982045,
 156.55093075269957,
 158.9990942355787,
 161.44725771845782,
 163.91094843406387,
 166.3746391496699,
 168.83832986527594,
 171.302020580882,
 173.765711296488,
 176.22940201209406,
 178.6930927277001,
 181.15678344330613,
 183.62047415891217,
 186.08416487451822,
 188.54785559012424,
 191.0115463057303,
 193.47523702133634,
 195.9389277369424,
 198.4026184525484,
 200.86630916815446,
 203.32999988376048,
 205.79369059936653,
 208.25738131497258,
 210.72107203057863,
 213.18476274618465,
 215.64845346179067,
 218.11214417739671,
 220.57583489300276,
 223.0395256086088,
 225.50321632421483,
 227.96690703982088,
 230.43059775542693,
 232.89428847103295,
 235.357979186639,
 237.82166990224502,
 240.2853606178511,
 242.74905133345712,
 245.21274204906314,
 247.67643276466922,
 250.14012348027524,
 252.60381419588128,
 255.06750491148733,
 257.5311956270933,
 259.99488634269943,
 262.4585770583054,
 277.4585770583054,
 279.9017244994749,
 282.34487194064434,
 284.78801938181374,
 287.2311668229832,
 289.67431426415266,
 292.11746170532206,
 294.5606091464915,
 297.0037565876609,
 299.4469040288304,
 301.89005146999983,
 304.3331989111693,
 306.7763463523387,
 309.21949379350815,
 311.6626412346776,
 314.10578867584707,
 316.5489361170165,
 318.992083558186,
 321.4352309993553,
 323.8783784405248,
 326.37274011537744,
 328.8671017902301,
 331.36146346508275,
 333.8558251399354,
 336.35018681478806,
 338.8445484896407,
 341.33891016449337,
 343.833271839346,
 346.3276335141987,
 348.82199518905134,
 351.316356863904,
 353.81071853875665,
 356.3050802136093,
 358.79944188846196,
 361.2938035633146,
 363.78816523816727,
 366.2825269130199,
 368.7768885878726,
 371.27125026272523,
 373.7656119375779,
 376.25997361243054,
 378.7543352872832,
 381.24869696213585,
 383.7430586369885,
 386.23742031184116,
 388.7317819866938,
 391.2261436615465,
 393.7205053363991,
 396.2148670112518,
 398.70922868610444,
 401.2035903609571,
 403.69795203580975,
 406.1923137106624,
 408.68667538551506,
 411.1810370603677,
 413.67539873522037,
 416.169760410073,
 418.6641220849257,
 421.1584837597784,
 423.652845434631]
```

**Comment by magland** [comment]
Okay that's helpful. But annoying :)
Do you think we can leave it as is for now and submit a new issue for making the adjustment?
Just wondering how important it is to remove the offset, for your purposes...

**Comment by magland** [comment]
Okay I'll work on this. I realize that it's going to be much easier to map to the correct bins on the python side (b/c of numpy utils) rather than try to do it in the browser.

Could you please open the request about the position marker in a separate issue?

**Comment by magland** [comment]
Here's the next iteration:

https://figurl.org/f?v=gs://figurl/spikesortingview-4&d=ipfs://bafkreicn6vkjkxy6drx6wm3trvgj2upnrpumopcj52usa7omeyim7zgaue&project=siojtbyvbw&label=Jaq_03_12_visualization_data

**Comment by edeno** [comment]
That looks great! The actual position may be one bin off from what I can tell, but I don't know if that's an artifact of looking at it way zoomed in?
