### ISSUE TITLE
Misaligned spikes

### ISSUE THREAD

**Issue by khl02007** [magland/sortingview#19]
When `detect_sign` of 0 is used in mountainsort4, we detect both upward and downward going spikes. Sometimes a single unit is split into two clusters (one centered at downward and the other centered at upward peak). As a result, these are misaligned and merging them leads to something unreasonable.

two such clusters that probably should be merged:
![image](https://user-images.githubusercontent.com/9277197/125142858-a4a31200-e0cd-11eb-8d2d-9a432392f7ea.png)
after merging:
![image](https://user-images.githubusercontent.com/9277197/125142942-df0caf00-e0cd-11eb-88cf-23058047d490.png)

this may be a mountainsort problem rather than sortingview problem, but is there a workaround?

**Comment by magland** [comment]
I think the best way to handle this is to add a post-processing step onto mountainsort that can identify these situations and automatically merge them (after alignment). The algorithmic steps would be:

1. Identify candidate pairs for merging (based on some criteria)
2. For each candidate pair, find the optimal temporal offset and test the merge putting all events into one cluster (after correcting for the alignment offset) and testing using isosplit whether it should be merged or stay split.

Could you share the link to the above example? If you don't want the link public, you can send via slack.

**Comment by khl02007** [comment]
@magland Here is the link: https://sortingview.vercel.app/workspace/sorting/R-99a0e1e9ddc9/S-1cea612c341e?workspace=c800c4cd5c451852f5656fec9c1ce36a335a84b7e0d15d66211f7686c420f131&channel=franklab

Would it be possible to identify candidate pairs for merging without first aligning them? I think this would be difficult. How about changing the order a bit?
1. Align every spike (I think using the max slope is considered better than max amplitude since the latter just depends on a single point)
2. Identify clusters that should (putatively) be merged (based on e.g. cosine similarity of the waveforms) 
3. Test out the merge with isosplit

**Comment by magland** [comment]
Looking at the cross-correlograms, it seems that these are being double-counted. You must be using detect sign of 0? There is a parameter in detection that controls how close in time spikes are aloud to be for detecting on the same channel. I can't remember if it is exposed in the parameters of mountainsort... but that may solve this particular issue.

![image](https://user-images.githubusercontent.com/3679296/125817464-c7adfb53-33fc-4958-97cd-9058d5f0d398.png)

**Comment by khl02007** [comment]
Yes, for this the `detect_sign` was 0 so we were detecting both upward and downward going spikes. The parameter you mentioned (`detect_interval`) is indeed exposed in MS4, but this still happens for some reason. Do you think this could be because the positive peak and the negative peaks are actually father apart than the `detect_interval` (and as a result they are considered different events)? What is the bin size of the cross correlogram? I think in this case `detect_interval` was 10 and the sampling rate was 30kHz, so would be a third of a millisecond.

**Comment by magland** [comment]
@khl02007 My guess is that the two peaks in that case are deparated by >10 timepoints. Please try again with detect_interval=20 and see if that remedies.
