### ISSUE TITLE
cross correlograms not popuating

### ISSUE THREAD

**Issue by MichaelCoulter** [magland/sortingview#201]
when i try to generate cross correlograms for 2 units using figurl, the plots just "waiting" and are not generated.

this is the link i am using: https://www.figurl.org/f?v=gs://figurl/spikesortingview-6&d=sha1://5dcdc136c2887bd48a629740b87aff1d2eb6bca7&project=lqqrbobsev&label=tonks20211024_.nwb_r1_r2_r3_5_franklab_tetrode_hippocampus

thanks.

**Comment by magland** [comment]
@MichaelCoulter 
When using the "live" CC view, you need a running sortingview backend in the project. I'd recommend you use the latest recommended way of generating the figurl, which uses a "precomputed" CC view, so you don't need a backend.
See:
https://github.com/magland/sortingview/tree/main/notebooks/workspace_example

**Comment by MichaelCoulter** [comment]
Okay, thanks. I will try the precomputed cross correlograms.
