### ISSUE TITLE
new pyvips package dependency

### ISSUE THREAD

**Issue by MichaelCoulter** [magland/sortingview#202]
hi Jeremy, i noticed a package called pyvips is now required when importing sortingview.⁠​ when i tried to import sortingview as part of spyglass this caused an error and i had to add it to my environment. is is possible for sortingview to be self-contained? thanks.

**Comment by magland** [comment]
Thanks for the heads up, I'll remove that dependency.

**Comment by magland** [comment]
@MichaelCoulter Okay, please upgrade to 0.9.9.
