### ISSUE TITLE
authorization error

### ISSUE THREAD

**Issue by MichaelCoulter** [magland/sortingview#206]
hi jeremy, im getting a new authorization error when i try to create a sortingview workspace. do you have any ideas on what this might be about? i have the latest version of sortingview and i think i have all the environment variables set correctly. thanks, mike

**the command im running**
# automatic curation
#mike_noise_only_10
auto_curation_params_name = 'mike_noise_only_10'

#for ginny
all_tet_list = np.array([1,2,4,5,7,8,11,12,13,14,15,16,17,20,21,22,25,26,27,28,31,
                         33,34,35,36,37,39,41,42,43,44,45,47,49,51,52,54,56,57,59,61,62,63,64])-1

for nwb_file_name in ['ginny20211027_.nwb','ginny20211029_.nwb','ginny20211101_.nwb',]:
    for tetrode in [0]:
        autocuration_key = (SpikeSorting & {'nwb_file_name' : nwb_file_name} & {'sort_group_id' : tetrode}
                            & {'sorter_params_name' : 'franklab_tetrode_hippocampus_30KHz_tmp'}
          & {'artifact_params_name': 'ampl_1500_prop_001_5ms'} & {'sorter' : 'mountainsort4'}
                            & {'sort_interval_name' : 'r1_r2_r3'}).fetch1('KEY')
        autocuration_key['curation_id'] = 0
        autocuration_key['waveform_params_name'] = 'default_whitened'
        autocuration_key['metric_params_name'] =  'JG_DG_no_peak_offset_min_spikes'
        autocuration_key['auto_curation_params_name'] = auto_curation_params_name

        ss.AutomaticCurationSelection.insert1(autocuration_key, skip_duplicates=True)
        ss.AutomaticCuration.populate([(ss.AutomaticCurationSelection & autocuration_key).proj()])

        auto_curation_id = (ss.AutomaticCuration & autocuration_key).fetch1('auto_curation_key')
        auto_curation_out_key = (ss.Curation & auto_curation_id).fetch1("KEY")

        ## add to sortingview workspace for manual curation
        ss.SortingviewWorkspaceSelection.insert1(auto_curation_out_key, skip_duplicates=True)
        ss.SortingviewWorkspace.populate(auto_curation_out_key)

**the error**

---------------------------------------------------------------------------
Exception                                 Traceback (most recent call last)
Input In [3], in <cell line: 9>()
     26 ## add to sortingview workspace for manual curation
     27 ss.SortingviewWorkspaceSelection.insert1(auto_curation_out_key, skip_duplicates=True)
---> 28 ss.SortingviewWorkspace.populate(auto_curation_out_key)
     29 #print('Tetrode', tetrode+1, ss.SortingviewWorkspace().url(auto_curation_out_key))
     30 
     31 # Populate CuratedSpikeSorting
     32 ss.CuratedSpikeSortingSelection.insert1(auto_curation_out_key, skip_duplicates=True)

File ~/anaconda3/envs/spyglass/lib/python3.9/site-packages/datajoint/autopopulate.py:230, in AutoPopulate.populate(self, suppress_errors, return_exception_objects, reserve_jobs, order, limit, max_calls, display_progress, processes, make_kwargs, *restrictions)
    226 if processes == 1:
    227     for key in (
    228         tqdm(keys, desc=self.__class__.__name__) if display_progress else keys
    229     ):
--> 230         error = self._populate1(key, jobs, **populate_kwargs)
    231         if error is not None:
    232             error_list.append(error)

File ~/anaconda3/envs/spyglass/lib/python3.9/site-packages/datajoint/autopopulate.py:281, in AutoPopulate._populate1(self, key, jobs, suppress_errors, return_exception_objects, make_kwargs)
    279 self.__class__._allow_insert = True
    280 try:
--> 281     make(dict(key), **(make_kwargs or {}))
    282 except (KeyboardInterrupt, SystemExit, Exception) as error:
    283     try:

File ~/spyglass/src/spyglass/spikesorting/sortingview.py:63, in SortingviewWorkspace.make(self, key)
     60     google_user_ids.append(google_user_id[0])
     62 # do
---> 63 workspace_uri, recording_id, sorting_id = _create_spikesortingview_workspace(recording_path=recording_path,
     64                                                                              sorting_path=sorting_path,
     65                                                                              merge_groups=merge_groups,
     66                                                                              workspace_label=workspace_label,
     67                                                                              recording_label=recording_label,
     68                                                                              sorting_label=sorting_label,
     69                                                                              metrics=metrics,
     70                                                                              curation_labels=curation_labels,
     71                                                                              google_user_ids=google_user_ids)
     73 # insert
     74 key['workspace_uri'] = workspace_uri

File ~/spyglass/src/spyglass/spikesorting/sortingview_helper_fn.py:98, in _create_spikesortingview_workspace(recording_path, sorting_path, merge_groups, workspace_label, recording_label, sorting_label, metrics, google_user_ids, curation_labels, similarity_matrix, raster_plot_subsample_max_firing_rate, spike_amplitudes_subsample_max_firing_rate)
     96 if google_user_ids is not None:
     97     workspace.create_curation_feed_for_sorting(sorting_id=sorting_id)
---> 98     workspace.set_sorting_curation_authorized_users(sorting_id=sorting_id, user_ids=google_user_ids)
    100 if curation_labels is not None:
    101     for unit_id, label in curation_labels.items():

File ~/sortingview/sortingview/workspace/Workspace.py:196, in Workspace.set_sorting_curation_authorized_users(self, sorting_id, user_ids)
    194 if feed is None:
    195     raise Exception('No sorting curation feed')
--> 196 kcl.set_mutable(f'sortingview/sortingCurationAuthorizedUsers/{feed.uri}', json.dumps(user_ids))

File ~/anaconda3/envs/spyglass/lib/python3.9/site-packages/kachery_cloud/mutable.py:19, in set_mutable(key, value, project_id)
     17 else:
     18     payload['projectId'] = get_project_id()
---> 19 response = _kacherycloud_request(payload)

File ~/anaconda3/envs/spyglass/lib/python3.9/site-packages/kachery_cloud/_kacherycloud_request.py:27, in _kacherycloud_request(request_payload)
     25 resp = requests.post(url, json=req)
     26 if resp.status_code != 200:
---> 27     raise Exception(f'Error in {payload["type"]} ({resp.status_code}) {resp.reason}: {resp.text}')
     28 response = resp.json()
     29 return response

Exception: Error in setMutable (500) Internal Server Error: Error: Invalid mutable key: sortingview/sortingCurationAuthorizedUsers/kachery-feed://iubwcqkgzdjj (0 sortingview)

**Comment by magland** [comment]
Requires latest kachery-cloud.
Working this out on slack.
