### ISSUE TITLE
figurl link leads to "Invalid figure data"

### ISSUE THREAD

**Issue by MichaelCoulter** [magland/sortingview#211]
i pulled the spyglass, sortingview, and spikeinterface repos on 9/24/22 however, when i generate a new sortingview workspace, the figURL link goes to a webpage that says "Invalid figure data" and does contain any data. any help would be appreciated, thanks.

command:
auto_curation_params_name = 'mike_noise_only_10'

for nwb_file_name in ['ginny20211024_.nwb']:
for tetrode in [0]:
autocuration_key = (SpikeSorting & {'nwb_file_name' : nwb_file_name} & {'sort_group_id' : tetrode}
& {'sorter_params_name' : 'franklab_tetrode_hippocampus_30KHz_tmp'}
& {'artifact_params_name': 'ampl_1500_prop_001_5ms'} & {'sorter' : 'mountainsort4'}
& {'sort_interval_name' : 'r1_r2'}).fetch1('KEY')
autocuration_key['curation_id'] = 0
autocuration_key['waveform_params_name'] = 'default_whitened'
autocuration_key['metric_params_name'] = 'JG_DG_no_peak_offset_min_spikes'
autocuration_key['auto_curation_params_name'] = auto_curation_params_name

    ss.AutomaticCurationSelection.insert1(autocuration_key, skip_duplicates=True)
    ss.AutomaticCuration.populate([(ss.AutomaticCurationSelection & autocuration_key).proj()])

    auto_curation_id = (ss.AutomaticCuration & autocuration_key).fetch1('auto_curation_key')
    auto_curation_out_key = (ss.Curation & auto_curation_id).fetch1("KEY")

    ## add to sortingview workspace for manual curation
    ss.SortingviewWorkspaceSelection.insert1(auto_curation_out_key, skip_duplicates=True)
    ss.SortingviewWorkspace.populate(auto_curation_out_key)
resulting URL:
figurl: https://figurl.org/f?v=gs://figurl/spikesortingview-9&d=sha1://c95dc9c943c8c62a08a84b04285399dca301fd9f&project=lqqrbobsev&label=ginny20211024_.nwb_r1_r2_0_franklab_tetrode_hippocampus

**Comment by magland** [comment]
See message on slack
