### ISSUE TITLE
Timeseries widget: the scale bar and label in the y-axis (voltage) are missing

### ISSUE THREAD

**Issue by magland** [magland/sortingview#22]
Originally part of #18

**Comment by magland** [comment]
@lfrank @khl02007
I could use some help designing the y-axis (voltage) label.
Note: the y-axis unit is not always voltage (e.g., whitened or simulated data), so I would not want to hard-code that label in there.
Should the axis be on all channels? Or just one? Where should it appear? Do we put tick marks? Do we want to toggle this on/off?

**Comment by lfrank** [comment]
My main concern is ticks and labeks for the ticks so we know the magnitudes of the values. I don’t think a y axis label is necessary, although in cases where it is known (e.g. data from an NWB timeseries with a units entry) one could use that.

I would always wants ticks and labels, but a toggle can’t hurt if that’s easy to add.

I’m not sure what you mean by all channels, though.

**Comment by khl02007** [comment]
@magland 
> Note: the y-axis unit is not always voltage (e.g., whitened or simulated data), so I would not want to hard-code that label in there.
When would we need to plot whitened data? or perhaps you're thinking of using the widget for a number of use cases beyond sortingview?

> Should the axis be on all channels? Or just one? 
All the channels have the same y-scale at the moment, so I think having it on just one would be sufficient

> Where should it appear? 
doesn't matter too much as long as it (the scale bar) doesn't obscure the data. 

> Do we put tick marks? 
on the axis or on the scale bar? provided we're going with the scale bar and it is of reasonable size, I don't think this matters too much

> Do we want to toggle this on/off?
You could implement this feature but seems also OK to just leave it on all the time

**Comment by magland** [comment]
This will be resolved by PRs #68 and #69
