### ISSUE TITLE
Add way to highlight intervals in TimeSeriesGraph

### ISSUE THREAD

**Issue by edeno** [magland/sortingview#222]
As discussed in our meeting it would be useful to have a way to highlight intervals in a time series. It would also be helpful to be able to control the opacity and color. Ideally it would take an ndarray of shape (n_events, 2) where each column would be a start and stop time.

**Comment by edeno** [comment]
Thanks @magland. I am using this and it works great. One thing that would be handy is the ability to control the opacity. Is that difficult?

**Comment by magland** [comment]
@edeno I think you should be able to do this using rgba string for the color. Like `color=rgba(50,50,255,0.5)`

**Comment by khl02007** [comment]
@magland 
It seems like this obscures the data behind it.
https://figurl.org/f?v=gs://figurl/spikesortingview-10&d=sha1://a03cc1bb7e23bbb3fe3cea59a0c541e407040d33&label=MS22%20lineared%20sorted%20spikes%20classifier

Is it because I added the interval series after adding the line series?

**Comment by edeno** [comment]
The order of operations matters. You can also adjust the opacity

**Comment by khl02007** [comment]
@magland also when you are zoomed in enough, the color of the interval disappears. 

https://figurl.org/f?v=gs://figurl/spikesortingview-10&d=sha1://c582fcdbbfead42ec951baa349afac5f0e9e27ee&label=MS22%20lineared%20sorted%20spikes%20classifier
