### ISSUE TITLE
subsampling correlograms to speed up calculations.

### ISSUE THREAD

**Issue by magland** [magland/sortingview#31]
See #30

**Comment by magland** [comment]
Determining the method of subsampling for correlograms.

Suppose we have a long recording of 100,000 seconds, and suppose we have 100,000 events for a particular unit (firing rate of 1Hz for simplicity). Suppose that we only need 1,000 events for good statistics, and suppose we are interested in a histogram spanning 100 ms. The subtlety is that there is a difference between 1,000 events sampled throughout the entire recording, verses considering the first 1,000 events (or 1,000 events from a continuous time chunk). In the former case of random sampling, we would expect (i think) only 100,000/10/1000 = 10 elements in the histogram, whereas in the latter case of contiguous sampling, we would expect (I think) 1,000/10 = 100 elements in the histogram.

This is just my intuition - it's better if we actually calculate an estimate. But my guess is that we are dealing with sqrt(n) items in the histogram for the random sampling method vs n items for sampling a continuous chunk.

The disadvantage of sampling a continuous chunk is that we are biased to a particular part of the recording. I therefore propose that we sample in the union of a set of random disjoint segments of duration 10 seconds each. Maybe by default we sample 100 10-second segments. Or maybe they don't need to be random, we could also sample systematically.

**Comment by lfrank** [comment]
@magland I think 100 10-second segments is a very reasonable starting case. In the context of sorting we're really looking for overall trends, not precision, so I think that should be fine.

**Comment by magland** [comment]
Subsampling for correlograms is now implemented for sortingview >= 0.2.30. Perhaps later we can have a toggle option for this. Also we'll want to indicate somewhere that the histograms are subsampled.
