### ISSUE TITLE
Document correlogram subsampling in app - and add opts for level of subsampling

### ISSUE THREAD

**Issue by magland** [magland/sortingview#37]
Subsampling for correlograms is now implemented for sortingview >= 0.2.30. Perhaps later we can have a toggle option for this. Also we'll want to indicate somewhere that the histograms are subsampled.

_Originally posted by @magland in https://github.com/magland/sortingview/issues/31#issuecomment-883294526_

**Comment by magland** [comment]
@jsoules I was thinking we need some sort of asterisk in the correlograms view that tells the user that subsampling has occurred. I was thinking a question mark icon in the corner that yields a popup window that has that info. 

For an example of this type of thing, see: https://github.com/magland/sortingview/blob/f111a7f7b704e9006482624bd5f1ee5b06daf797/src/labbox-react/HomePage/ChannelSection.tsx#L32

**Comment by jsoules** [comment]
Fixed in PR #51.
