### ISSUE TITLE
Unit numbers for unit waveforms

### ISSUE THREAD

**Issue by magland** [magland/sortingview#39]
transferred from: https://github.com/flatironinstitute/labbox-ephys/issues/472

**Comment by magland** [comment]
Copied from labbox-ephys issue:

> On the waveform display, the unit numbers could go much closer to the top left electrode circle to save space.

**Comment by magland** [comment]
@lfrank, not sure I can reproduce. See screenshot:
![image](https://user-images.githubusercontent.com/3679296/126665303-eff38e56-df69-4d2e-85b3-0b44f02697c5.png)

Could you provide a screenshot showing the wasted space?

**Comment by lfrank** [comment]
I can’t generate one right now, but do you have a tetrode version you could try? That was where there was quite a lot of extra space.

**Comment by magland** [comment]
Is this the kind of thing you were seeing?

![image](https://user-images.githubusercontent.com/3679296/126690848-a0d51846-6885-47b4-86e5-e51dac1dc85b.png)

I do see there is extra space in some cases.

**Comment by lfrank** [comment]
Yes, although it might have been more pronounced in the Jupyter widget. In any case, having the Unit numbers closer to the traces and (in a perfect world) having an option for displaying these in a row (as in mountainview) would be great.
