### ISSUE TITLE
Merged units should have only one label

### ISSUE THREAD

**Issue by magland** [magland/sortingview#40]
transferred from: https://github.com/flatironinstitute/labbox-ephys/issues/467

**Comment by magland** [comment]
Copied from labbox-ephys issue:

> Once a set of units are merged, only the lowest number unit should be listed in the labelsByUnit so that it matches the curated_sorting_extractor.

> As we discussed, the best way to do this might be to have the labels as a second output when one gets the curated sorting extractor.

**Comment by magland** [comment]
I don't think user should be interacting with labelsByUnit. That's internal data I think.

@lfrank, we should chat about this again so that I am clear on what is being requested.

**Comment by lfrank** [comment]
@magland. We had been using labelsByUnit to populate the CuratedSorting() table, but looking at the newest version of the code, that has been changed to use the get_sorting_curation function, so I think this issue can be closed for the moment.
