### ISSUE TITLE
Curation completed button

### ISSUE THREAD

**Issue by magland** [magland/sortingview#41]
transferred from: https://github.com/flatironinstitute/labbox-ephys/issues/463

**Comment by magland** [comment]
Pasted from labbox-ephys issue:

> It would be helpful if the user could click a "curation completed" or just "Completed" button which would add a tag to that effect. That would allow us to look for that tag in the workspace and only add to the CuratedSpikeSorting table when the curation was ready.

**Comment by magland** [comment]
What I suggest:

* Add sorting curation actions called something like "CLOSE_CURATION" and "REOPEN_CURATION"
* If curation is open (the default) a "Close curation" button appears on the GUI
* If curation closed, a "Reopen curation" button appears
* When the curation is closed, further curation actions (adding labels) are not permitted in the GUI

The following files will need to be updated:
* CurationControl.tsx (GUI components)
* SortingCuration.ts and workspaceReducer.ts (the sorting curation reducer in typescript)
* workspace.py: see _get_sorting_curation()

**Comment by jsoules** [comment]
Closed by PR #74.
