### ISSUE TITLE
Delete workspace from backend

### ISSUE THREAD

**Issue by khl02007** [magland/sortingview#5]
Hi @magland, how would I delete a workspace added to the backend?

**Comment by khl02007** [comment]
Actually what I meant to ask is: is there a way to delete workspace from the sortingview app, e.g. from the view below? I assume right now we would have to delete the workspace feed from kachery storage?
![image](https://user-images.githubusercontent.com/9277197/124988469-e01cde00-dff2-11eb-9e8d-80578b1479ca.png)

**Comment by magland** [comment]
@khl02007 you still can't delete them from the GUI, but now the GUI contains instructions for both adding/removing workspaces.

You'll need to upgrade backend to >= 0.2.26 for the remove script to work.

It also shows how to get the list of workspaces from a Python script.

Once you confirm this works, I will close the issue.

**Comment by khl02007** [comment]
It seems like it's not working. Just deleted a workspace named `kyu` and it still shows up on the web app (though it is gone in the list of workspaces). By the way, I think there is an error in the example script; to list workspaces,`sortingview.workspace_names` doesn't work; need to do 
```
workspace_list = sortingview.WorkspaceList(list_name='default')
workspace_list.workspace_names() 
```

<img width="1124" alt="image" src="https://user-images.githubusercontent.com/9277197/126018413-79e066dc-139a-4de4-81f8-930eedfe42e0.png">

**Comment by magland** [comment]
Are you sure that `sortingview.workspace_names` does not work? Please try on the latest version. Also, please confirm on latest version that removing still does not work.

**Comment by khl02007** [comment]
@magland Looks like the latest sortingview version is 0.2.29 on the web app but the latest that is deployed is 0.2.27. Can you deploy the latest? I will try again after that

**Comment by magland** [comment]
Should be up to date now.

**Comment by khl02007** [comment]
`sortingview.workspace_names` still does not work
<img width="1179" alt="image" src="https://user-images.githubusercontent.com/9277197/126410077-3292fd03-e2ce-4faf-a3c6-8b3eeef7f59a.png">

also, the code snippet for deleting workspace
```
import sortingview

# replace "new-workspace" with the name of the workspace to remove
workspace_name = 'despereaux20191125_S801LRZBWZ.nwb'

workspace_list = sortingview.WorkspaceList(list_name='default')
workspace_list.remove_workspace(name=workspace_name)
```
finishes running and the workspace is indeed gone from the list accessed with
```
workspace_list = sortingview.WorkspaceList(list_name='default')
workspace_list.workspace_names() 
```
but still shows up on the web app (last one in the image below)

<img width="1373" alt="image" src="https://user-images.githubusercontent.com/9277197/126410259-1ddc323a-85ac-48a5-a8e2-87766da267da.png">

**Comment by magland** [comment]
This will be resolved once we have migrated to new workspace list system. Closing.
