### ISSUE TITLE
sortingview_workspace_list_subfeed query is not dependent on channel

### ISSUE THREAD

**Issue by magland** [magland/sortingview#67]
@jsoules, we will need to discuss this.

The problem is that if two channels share the same bucket, then they will share the same cache for query task results.

**Comment by jsoules** [comment]
Per our discussion today, current solution suggestion is to organize task results under a channel-specific subdirectory within the kachery structure.

We discussed whether it would make sense to continue sharing cache space for pure-computation tasks, but the advantages of consistent handling for all tasks (& the risks of confusion from different implementations of tasks registered with the same name, etc) seemed to outweigh the unlikely advantage of reduced computational time when a desired task result happens to be also available on a channel that shares the same cloud storage resource.

**Comment by magland** [comment]
@jsoules, I made this change and pushed directly to main branches of sortingview and kacheryhub. I did not create a PR because I wanted to make the change live so that I could make sure it all worked together. I also used gsutil to copy the files in the bucket as a one-off operation to minimize the inconvenience. Everything seems to be working as far as I can see so I will close this issue.
