### ISSUE TITLE
Suggestions for improving the average waveforms widget

### ISSUE THREAD

**Issue by khl02007** [magland/sortingview#8]
![image](https://user-images.githubusercontent.com/9277197/124196899-31245380-da82-11eb-8bf4-d67c8a05b96b.png)
* it seems like the waveforms at the last 15 channels are shown by default; would be more informative if N channels before and after the peak channel were shown instead; would also be nice if the channel number is displayed so that we know which channels we are looking at
* right now the waveforms are very small when sorting data with many channels; would be better if we could zoom in
* right now it is difficult to compare the waveforms of two selected units; would be nice if they could be superposed (or at least put side by side and hide the other units not being compared)

**Comment by magland** [comment]
Closing because these are handled by other issues.
