### ISSUE TITLE
Show All Units doesn't work

### ISSUE THREAD

**Issue by khl02007** [magland/sortingview#89]
Clicking show all units in Units Table gives white screen:

https://sortingview.vercel.app/workspace/sorting/R-c5089c48b72f/S-816a8e175985?workspace=e5c306c436a9f75fd97a20d832cd54d8243d516da53cbfe86270f11e98ee8b26&channel=franklab

**Comment by magland** [comment]
I pushed a fix to this. No need to restart backend.
