### ISSUE TITLE
Hide rejected does not work

### ISSUE THREAD

**Issue by lfrank** [magland/sortingview#9]
Clicking it seems to have no effect.

**Comment by magland** [comment]
This has now been fixed (GUI only change, no need to update the backend for this fix).

"Hide rejected", and "Show accepted only" should both work now. However, I disabled the other option to show only those units corresponding to visible electrodes. That will involve some more work to get working again.

**Comment by magland** [comment]
Disabled these options once again because I think it is causing the browser to hang.

**Comment by lfrank** [comment]
Sounds good. I’ll be able to test again in ~30 minutes.

**Comment by magland** [comment]
This should be fixed now in version >= 0.2.16
