### ISSUE TITLE
'Deselect selected` button

### ISSUE THREAD

**Issue by khl02007** [magland/sortingview#91]
Right now when the user selects a number of units in the Units Table and then clicks on a curation label, the cells remain selected. The user then has to deselect each of these individually before being able to select a new cell. Would be nice if there was a button that does the deselecting of selected units.

**Comment by jsoules** [comment]
Hi Kyu,

The "select all" checkbox (at the top left of the units table--the checkbox in line with the table headers) will deselect all units if they're all selected. So if you click it twice it will select everything, then deselect everything. Would that accomplish what you're looking for?

![image](https://user-images.githubusercontent.com/2347301/127877391-78925a71-54c8-441e-b48d-a9ec19e55cd4.png)

**Comment by khl02007** [comment]
Yes will just click select all button twice @acomrie

**Comment by acomrie** [comment]
@khl02007 thank you! The double clicking select-all/deselect-all is what I have been using for now, and I think this solution per @jsoules suggestion will be even better once things can be sped up a bit. At the moment, though, I find that it can be pretty laggy to select all and deselect all, especially when there are many units. I think there are already other issues open related to slowness - is your instinct that all the types of slowness in interacting with the units table are related to the same underlying issue? In which case we can leave it up to the other issues to address it hopefully
