### ISSUE TITLE
Update code-snippet-markdown components to standardize interpolation, copy-to-clipboard, syntax-wrapping functionality

### ISSUE THREAD

**Issue by jsoules** [magland/sortingview#94]
`ImportRecordingsInstructions.tsx` and `SortingInstructions.tsx` both use value interpolation, copy-to-clipboard functionality, and code-wrapping. These are implemented locally to those two files.

Because these features are likely to be useful in a broader context, we should centralize them in the `Markdown.tsx` and related components.

**Comment by magland** [comment]
Closing because I think this is done.
