### ISSUE TITLE
function for parsing kachery uri

### ISSUE THREAD

**Issue by magland** [magland/sortingview#96]
If we're going to need to extract semantically meaningful parts of the URIs generated by kachery-client, we should probably have a method within kc that can parse the URI and return the parts through its own definition. It'll be clearer to read, and also more resilient if we should find a need to change the format.

_Originally posted by @jsoules in https://github.com/magland/sortingview/pull/95#discussion_r682657570_

**Comment by magland** [comment]
@jsoules, I propose

```python
result = kc.parse_uri(kachery_uri)
assert result.algorithm == 'sha1'
sha1 = result.hash
```

So that allows us to parse and return more info (like manifest, chunkof, etc) at a later time. But for now, maybe just algorithm and hash.

The implementation could go something like this

```
class ParseUriResult:
    algorithm: str = ''
    hash: str = ''
    def __init__(self, *, algorithm: str, hash: str):
        ...

def parse_uri(uri: str):
    ... # do the parsing here
    x = ParseUriResult(algorithm=algorithm, hash=hash)
```

Or maybe there's a better pythonic way to do this type of thing?

**Comment by jsoules** [comment]
Properly this is an issue against the kacheryhub/kachery-client repo; I've implemented that there & filed a (fairly basic) PR against that repository.
